# Generated by Django 6.0.6 on 2026-10-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisory', '0010_alter_farmprofile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text="IANA timezone of the station's timestamps and of its calendar day.", max_length=60)),
                ('wind_height_m', models.FloatField(default=2.0, help_text='Anemometer height above ground (m). Used to convert wind to 2 m / 10 m.')),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(help_text='The farm whose fetched weather this station is used to validate.', on_delete=django.db.models.deletion.CASCADE, related_name='weather_stations', to='advisory.farmprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('lead_days', models.PositiveSmallIntegerField()),
                ('issued_at', models.DateTimeField()),
                ('source', models.CharField(default='open_meteo', max_length=30)),
                ('temp_max_c', models.FloatField(blank=True, null=True)),
                ('temp_min_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('rainfall_mm', models.FloatField(blank=True, null=True)),
                ('solar_mj_m2', models.FloatField(blank=True, null=True)),
                ('wind_kmh', models.FloatField(blank=True, null=True)),
                ('et0_mm', models.FloatField(blank=True, null=True)),
                ('precipitation_probability_pct', models.FloatField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to='advisory.farmprofile')),
            ],
            options={
                'ordering': ['target_date', 'lead_days'],
                'constraints': [models.UniqueConstraint(fields=('farm', 'target_date', 'lead_days'), name='uniq_snapshot_farm_target_lead')],
            },
        ),
        migrations.CreateModel(
            name='StationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temp_c', models.FloatField(blank=True, null=True)),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, help_text='Rain that fell in this interval (mm).', null=True)),
                ('wind_ms', models.FloatField(blank=True, help_text="Wind speed at the station's anemometer height (m/s).", null=True)),
                ('solar_wm2', models.FloatField(blank=True, help_text='Mean incoming shortwave radiation (W/m2).', null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='validation.weatherstation')),
            ],
            options={
                'ordering': ['timestamp'],
                'constraints': [models.UniqueConstraint(fields=('station', 'timestamp'), name='uniq_station_timestamp')],
            },
        ),
    ]
